# -*- coding: utf-8 -*-
"""Machine Learning tutorials

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bEhEYJMMUXl3zlBKRcTAk6uPXOLxgMfU
"""

import matplotlib.pyplot as plt
import numpy as np 
from sklearn import datasets, linear_model, model_selection

X, y = datasets.load_diabetes(return_X_y=True)
print(X.shape, X[0])

# Here we can see if the machine can help determine a logical split beteen the numbers in this dataset. 
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size = 0.33)
model = linear_model.LinearRegression()
model.fit(X_train, y_train)
# Model.fit is often used in machine learning libraries. 
print(model.fit(X_train, y_train))
print(model)

# We can also make a prediction using ... model.predict(X or whatever here)
#print(model.predict(X_train))

plt.scatter(X_test,  color = 'black')
plt.plot(X_test, yu_pred, color = 'blue', linewidth = 3)
plt.xlabel('Scaled BMIs')
plt.ylabel('Disease Progression')
plt.title('A Graph Plot Showing Diabetes Progression Against BMI')
plt.show()

# Building a web app for a ML Model 

import pandas as pd 
import numpy as np



