# -*- coding: utf-8 -*-
"""Hello world

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vIYgLa8ib3Fvjgkvi2P0aj1tVS5h0X62
"""

def function(word): 
  print("Hello world")
function(1)
  
